[package]
name = "chronicle-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
chronicle-core = { path = "../../1-primitives/chronicle-core" }
anyhow = "1"

[[bin]]
name = "archive-tap"
path = "src/main.rs"