[package]
name = "chronicle-access"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
chronicle-core = { path = "../../1-primitives/chronicle-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
zstd = "0.13"
clap = { version = "4.5.54", features = ["derive"] }
